### ISSUE TITLE
Using 'choice' as name for a form does not work anymore

### ISSUE THREAD

**Issue by hvanoch** [oroinc/platform#1040]
**Summary**  
In `src/Oro/Bundle/DashboardBundle/EventListener/WidgetConfigurationLoadListener.php:64` "choice" is being used as type, but this does not work anymore in the current symfony version and should be changed to `Symfony\Component\Form\Extension\Core\Type\ChoiceType:class` 

**Steps to reproduce**  
Update to latest symfony 4.4 go to dashboard page and add a grid as widget. Something like: 
```
dashboards:
  widgets:
    rental_widget:
      label: Rental overview
      acl: oms_rental_view
      description: This widgets shows all rentals
      route: oro_dashboard_grid
      route_parameters:
        gridName: rental-grid
        widget: rental_widget
```

**Actual Result**
Error being thrown on widget configuration screen:
![image](https://user-images.githubusercontent.com/6741991/95562398-67193780-0a1c-11eb-932d-df392d860b2a.png)

**Expected Result**  
Form that shows up

**Details about your environment**
- Oro 4.1.9
- PHP 7.3
- MySql 8.0
