### ISSUE TITLE
Datagrid Default filter not working with empty value

### ISSUE THREAD

**Issue by sadortun** [oroinc/platform#1042]
**Summary**  
Hi Guys,

We are using a default filter type on some fields in the `contact-grid`.
https://github.com/oroinc/platform/blob/4.1/src/Oro/Bundle/FilterBundle/Resources/doc/reference/grid_extension.md#string-filter

```yml
datagrids:
  contacts-grid:
    filters:
      default:
        firstName: { value: '',  type: Oro\Bundle\FilterBundle\Form\Type\Filter\TextFilterType::TYPE_STARTS_WITH }
        lastName:  { value: '',  type: Oro\Bundle\FilterBundle\Form\Type\Filter\TextFilterType::TYPE_STARTS_WITH }
        email:     { value: '',  type: Oro\Bundle\FilterBundle\Form\Type\Filter\TextFilterType::TYPE_STARTS_WITH }
```

I am not sure when the issue started exactly, but it seems that contacts that have an empty value (first, last or email) are no longer displayed in the grid.

After some investigation, we found out that the SQL generated look like this

```sql
SELECT .... 
FROM orocrm_contact o0_
.....
WHERE
    o0_.first_name LIKE '%' AND o0_.last_name LIKE '%' 
```

After looking into `StringFilter::parseValue()`

```php
            case TextFilterType::TYPE_STARTS_WITH:
                return sprintf('%s%%', $value);
```

The problem come from the fact that when `parseData()` is called `$data['value'] = null;`, and the filter explicitly look for a `''` value.

I had a look at every filters that implement `AbstractFilter::parseData()` and all of them `return false` when  `!$data['value']` or `empty($data['value']`

I am not sure why the change was made back in da7d585bf1ad4e964f30c6730c17ea644620bdda,  but i would recommend reverting it.

```diff
    protected function parseData($data)
    {
        $type = isset($data['type']) ? $data['type'] : null;
        if (!in_array($type, [FilterUtility::TYPE_EMPTY, FilterUtility::TYPE_NOT_EMPTY])
-            && (!is_array($data) || !array_key_exists('value', $data) || $data['value'] === '')
+            && (!is_array($data) || !array_key_exists('value', $data) || empty($data['value'])
        ) {
            return false;
        }

        $data['type'] = $type;
        $data['value'] = $this->parseValue($data['type'], $data['value']);

        return $data;
    }
```

**Steps to reproduce**  

**Actual Result**
```sql
SELECT .... 
FROM orocrm_contact o0_
.....
WHERE
    o0_.first_name LIKE '%' AND o0_.last_name LIKE '%' 
```
**Expected Result**  
```sql
SELECT .... 
FROM orocrm_contact o0_
.....
WHERE
....
```
**Details about your environment**
- OroPlatform version: 4.1.8
- PHP version: 7.4
- Database Mysql

**Additional information**
