### ISSUE TITLE
Segment doesn't show results if Entity.anyVirtualRelation.anyDictionaryField is used in filter

### ISSUE THREAD

**Issue by scapital** [oroinc/platform#746]
Hi Guys,

Here is STR that can be done without creating a custom entity.

1. Add to config/oro/entity.yml following configs
```yml
oro_entity:
    virtual_relations:
        Oro\Bundle\ContactBundle\Entity\Contact:
            exampleOfBrokeRelation:
                relation_type: oneToMane
                related_entity_name: Oro\Bundle\AddressBundle\Entity\Region
                label: 'broke_relation.label'
                query:
                    join:
                        left:
                            exampleOfBrokeRelation:
                                join: 'Oro\Bundle\AddressBundle\Entity\Region'
                                alias: task
```
2. Create a segment like this
![selection_125](https://user-images.githubusercontent.com/7324854/29876268-f668b462-8da4-11e7-9db3-85c8d491712e.png)
3. Go to segment view.

As a result you wont see anything. In logs you can see following:
```
[2017-08-30 16:50:33] app.ERROR: Getting grid data failed. {"exception":"[object] (Doctrine\\ORM\\Query\\QueryException(code: 0): [Semantical Error] line 0, col 523 near 'Oro\\Bundle\\AddressBundle\\Entity\\Region': Error: 'Oro\\Bundle\\AddressBundle\\Entity\\Region' is not defined. at /path/to/app/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:63, Doctrine\\ORM\\Query\\QueryException(code: 0): SELECT t1.firstName as c1, t1.id, IDENTITY(t1.businessUnit) as t1_owner_id, IDENTITY(t1.organization) as t1_organization_id FROM Oro\\Bundle\\ContactBundle\\Entity\\Contact t1 WHERE t1.id IN(SELECT DISTINCT ts326763971.id FROM Oro\\Bundle\\ContactBundle\\Entity\\Contact ts326763971 LEFT JOIN Oro\\Bundle\\AddressBundle\\Entity\\Region ts1863203432 WHERE EXISTS(SELECT dictionary1251115205.id FROM Oro\\Bundle\\ContactBundle\\Entity\\Contact dictionary1251115205 LEFT JOIN Oro\\Bundle\\AddressBundle\\Entity\\Region dictionary1154212585 WHERE Oro\\Bundle\\AddressBundle\\Entity\\Region = :dictionary20644148 AND dictionary1251115205.id = ts326763971.id)) ORDER BY t1.id ASC, t1.id ASC at /path/to/app/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:41)"} []
```
In our project we are using custom entity as a virtual relation(related_entity_name), result is same.
It happens with all 'virtualRelation.dictionaryField' in filter.

Also, maybe it will help you.
As a solution, I've tried replace these [code](https://github.com/oroinc/platform/blob/master/src/Oro/Bundle/QueryDesignerBundle/QueryDesigner/AbstractQueryConverter.php#L789-L791) to these
```php
if (isset($this->virtualColumnExpressions[$columnName])) {
	$mainTableAlias = explode('.', $this->virtualColumnExpressions[$columnName])[0];
	$mainEntityJoinId = array_flip($this->tableAliases)[$mainTableAlias];
} else {
	$mainEntityJoinId = $this->getParentJoinIdentifier(
		$this->joinIdHelper->buildColumnJoinIdentifier($columnName)
	);
}
```
and remote [these](https://github.com/oroinc/platform/blob/master/src/Oro/Bundle/QueryDesignerBundle/QueryDesigner/AbstractQueryConverter.php#L777-L780)

But it was changed logic of joins of 'non-virtual' fields, so, we refused from it.

Thanks!

**Comment by sergeyz** [comment]
Hi, @scapital!

`relation_type: oneToMane` should be fixed to `relation_type: oneToMany` and add `condition` and `conditionType` to your join please, it's not possible to do join without association and with condition missing, like

```
    virtual_relations:
        Oro\Bundle\CampaignBundle\Entity\Campaign:
            trackingEvent:
                relation_type: oneToMany
                related_entity_name: Oro\Bundle\TrackingBundle\Entity\TrackingEvent
                label: oro.tracking.trackingevent.entity_label
                query:
                    join:
                        left:
                            - { join: 'Oro\Bundle\TrackingBundle\Entity\TrackingEvent', alias: trackingEvent, conditionType: 'WITH', condition: 'trackingEvent.code = entity.code' }

```
