### ISSUE TITLE
Multiple embedded form in a Bundle with separate layout for each

### ISSUE THREAD

**Issue by scapital** [oroinc/platform#749]
Hi Guys,

There is any way to have multiple embedded forms(https://github.com/oroinc/platform/tree/2.3/src/Oro/Bundle/EmbeddedFormBundle) in a bundle with separate layout for each?

All embedded forms are used embedded_default/oro_embedded_form_submit as theme/route, therefore if 
I will define a layout for one form, for example as in docs, 
```yml
layout:
    actions:
        - @move:
            id:        embedded_form_email
            siblingId: embedded_form_firstName
            prepend:   true                     # place moved block before sibling

    conditions:
        @eq:
            - $context.embedded_form_type
            - 'acme_demo.form.embedded_form' # form type name in container
```
I can't defined another layout for another form in same Bundle.

Theme is hardcoded https://github.com/oroinc/platform/blob/2.3/src/Oro/Bundle/EmbeddedFormBundle/Manager/EmbedFormLayoutManager.php#L70
Route name is taken from a request https://github.com/oroinc/platform/blob/2.3/src/Oro/Bundle/LayoutBundle/Layout/Extension/RouteContextConfigurator.php#L38
Refactor the logic for some form looks dirty.
How can I solve this in a `clean` way?

I know about `Oro\Bundle\EmbeddedFormBundle\Form\Type\CustomLayoutFormInterface`, but it was marked as deprecated and implementation `Oro\Component\Layout\LayoutUpdateInterface` in a FormType won't take any effect.

Thanks!
