### ISSUE TITLE
DetailedLogsHandler exception

### ISSUE THREAD

**Issue by dimonixx** [oroinc/platform#763]
Hi

i've created log handler in app.yml 

```
monolog:
  channels: ["extract"]
  handlers:
    extract:
      level: DEBUG
      type: stream
      path: "%kernel.logs_dir%/extract.log"
      channels: ["extract"]
```

trying to log an error with Logger::addError() method i'm getting following error:

```
Exception trace:
 () at /opt/local/var/www/madia/gameworld.local/vendor/oro/platform/src/Oro/Bundle/LoggerBundle/Monolog/DetailedLogsHandler.php:63
 Oro\Bundle\LoggerBundle\Monolog\DetailedLogsHandler->write() at /opt/local/var/www/madia/gameworld.local/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php:37
 Monolog\Handler\AbstractProcessingHandler->handle() at /opt/local/var/www/madia/gameworld.local/vendor/monolog/monolog/src/Monolog/Logger.php:337
 Monolog\Logger->addRecord() at /opt/local/var/www/madia/gameworld.local/vendor/monolog/monolog/src/Monolog/Logger.php:404
 Monolog\Logger->addError() at /opt/local/var/www/madia/gameworld.local/src/Madia/Bundle/MconnectBundle/EventListener/JobExecutionSubscriber.php:84
```

This happens only in production environment
