### ISSUE TITLE
Unable to run functional test

### ISSUE THREAD

**Issue by xgitxhubx** [oroinc/platform#770]
Environment:

- Symfony version: 2.8.13
- https://github.com/oroinc/platform-application

Error:
`Symfony\Component\Config\Definition\Exception\InvalidConfigurationException: You are not allowed to define new elements for path "security.firewalls". Please define all elements for this path in one config file.`

It'll work if I comment out this line (ie: don't import security.yml):
https://github.com/oroinc/platform-application/blob/master/app/config/config.yml#L3
and the content of security.yml:
```
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
```

**Comment by NiMias** [comment]
Hello, @xgitxhubx !

1) Please, try to search the word "security" in all .yml files in your project directory (to ensure, that you don't have, actually, another 'security' config). And, please, provide results here.

2) What, exactly, test you're trying to run? Your own? Have you successfully run other functional tests on your application before?

**Comment by xgitxhubx** [comment]
Hi @NiMias ,

Environments:

```
Symfony version: 2.8.13
oro/redis-config | 2.0.0-beta.1 | MIT
oro/doctrine-extensions | 1.1.2 | MIT
oro/marketing | 2.4.2 | OSL-3.0
oro/crm-task-bundle | 2.4.0 | OSL-3.0
oro/crm-call-bundle | 2.4.0 | OSL-3.0
oro/calendar-bundle | 2.4.0 | OSL-3.0
oro/platform-serialised-fields | 2.4.0 | OSL-3.0
oro/commerce-crm | 1.4.1 | OSL-3.0
oro/platform-enterprise | 2.4.3 | Commercial
oro/crm-mail-chimp | 2.4.2 | OSL-3.0
oro/crm-abandoned-cart | 2.4.0 | OSL-3.0
oro/crm-dotmailer | 2.4.0 | OSL-3.0
oro/crm-enterprise | 2.4.0 | Commercial
oro/crm-hangouts-call-bundle | 2.4.0 | OSL-3.0
oro/crm-magento-embedded-contact-us | 2.4.0 | OSL-3.0
oro/crm-pro-ldap-bundle | 2.4.0 | OSL-3.0
oro/platform | 2.4.5 | MIT
oro/commerce | 1.4.5 | OSL-3.0
oro/customer-portal | 2.4.4 | OSL-3.0
oro/commerce-enterprise | 1.4.4 | Commercial
oro/crm | 2.4.5 | OSL-3.0
oro/crm-zendesk | 2.4.2 | OSL-3.0
```

1. Search results:

app/config/security.yml:
```
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
```

app/config/security_test.yml:
```
security:
    acl:
        connection: default
        cache:
            id: security.acl.cache.doctrine
            prefix: sf2_acl_

    firewalls:
        main:
            pattern: ^%web_backend_prefix%/
            organization-http-basic:
                realm: "Secured REST Area"
            provider: oro_user
            http-basic: false
            organization-form-login: false
            logout: false
            organization-remember-me: false
            anonymous: true

        frontend:
            pattern: ^/
            organization-http-basic:
                realm: "AccountUser REST Area"
            provider: commerce_customer_user
            http-basic: false
            organization-form-login: false
            logout: false
            organization-remember-me: false
            anonymous: true

        frontend_secure:
            pattern: ^/
            organization-http-basic:
                realm: "Secured AccountUser REST Area"
            provider: commerce_customer_user
            http-basic: false
            organization-form-login: false
            logout: false
            organization-remember-me: false
            anonymous: true

```

vendor/oro/commerce/src/Oro/Bridge/MarketingCommerce/Resources/config/oro/app.yml:
```
security:
    firewalls:
        # override pattern
        tracking_data:
            pattern: ^%web_backend_prefix%/tracking/data/create

```

vendor/oro/crm-pro-ldap-bundle/Resources/config/oro/app.yml:
```
security:
    firewalls:
        main:
            oro-ldap-organization-form-login:
                csrf_provider:              form.csrf_provider
                check_path:                 oro_user_security_check
                login_path:                 oro_user_security_login
```

vendor/oro/customer-portal/src/Oro/Bundle/CustomerBundle/Resources/config/oro/app.yml:
```
security:
    providers:
        commerce_customer_user:
            id: oro_customer.security.provider

    encoders:
        Oro\Bundle\CustomerBundle\Entity\CustomerUser: sha512

    firewalls:
        frontend:
            # @todo: secure api BB-1206
            pattern:                        ^/
            provider:                       commerce_customer_user
            context:                        customer_identity
            organization-form-login:
                csrf_provider:              form.csrf_provider
                check_path:                 oro_customer_customer_user_security_check
                login_path:                 oro_customer_customer_user_security_login
                default_target_path:        oro_frontend_root
            logout:
                path:                       oro_customer_customer_user_security_logout
                invalidate_session:         false
            organization-remember-me:
                key:                        %secret%
                name:                       OROCOMMERCE
                lifetime:                   2592000   # stay logged for 30 days
                httponly:                   true
            anonymous_customer_user:        true
```

vendor/oro/customer-portal/src/Oro/Bundle/FrontendBundle/Resources/config/oro/app.yml:
```
security:
    firewalls:
        assets:
            pattern:                        ^/(css|images|js)/
            security:                       false

        install:
            pattern:                        ^/installer
            security:                       false
            anonymous:                      true

        # override pattern
        wsse_secured:
            pattern:                        ^%web_backend_prefix%/api/rest.*

        # override pattern
        api_wsse_secured:
            pattern:                        ^%web_backend_prefix%/api/(?!(doc|rest))($|.*)

        # override pattern
        login:
            pattern:                        ^%web_backend_prefix%/user/(login|reset-request|send-email|check-email)$

        # override pattern
        reset_password:
            pattern:                        ^%web_backend_prefix%/user/reset/*

        # override pattern
        embedded_form:
            pattern:                        ^%web_backend_prefix%/embedded-form/(submit|success)

        # override pattern and config
        main:
            pattern:                        ^%web_backend_prefix%/
            organization-form-login:
                default_target_path:        oro_default
            logout:
                invalidate_session:         false
                target:                     oro_default
```

vendor/oro/marketing/src/Oro/Bundle/TrackingBundle/Resources/config/oro/app.yml:
```
security:
    firewalls:
        tracking_data:
            pattern:   ^/tracking/data/create
            provider:  chain_provider
            anonymous: true
```

vendor/oro/platform-enterprise/src/Oro/Bundle/UserProBundle/Resources/config/oro/app.yml:
```
security:
    firewalls:
        main:
            two-factor:
                login_path: oropro_user_two_factor_auth
                check_path: oropro_user_two_factor_check
                failure_path: oro_user_security_login
                auth_parameter: _auth_code
```

vendor/oro/platform/src/Oro/Bundle/ApiBundle/Resources/config/oro/app.yml:
```
security:
    firewalls:
        api_wsse_secured:
            pattern: ^/api/(?!(rest|doc)($|/.*))
            stateless:  true
            wsse:
                lifetime: 3600
                realm:    "Secured API"
                profile:  "UsernameToken"
            context: main
```

vendor/oro/platform/src/Oro/Bundle/DistributionBundle/Resources/config/security.yml:
```
security:
    acl:
        connection: default
        cache:
            id: security.acl.cache.doctrine
            prefix: sf2_acl_

    providers:
        oro_user:
            entity: { class: OroDistributionBundle:Security\User, property: username }

    encoders:
        Oro\Bundle\DistributionBundle\Entity\Security\User: sha512

    firewalls:
        dev:
            pattern:                        ^/(_(profiler|wdt)|css|images|js)/
            security:                       false

        login:
            pattern:                        ^/login$
            security:                       false

        main:
            pattern:                          ^/
            provider:                         oro_user
            form_login:
                check_path:                     oro_distribution_security_login_check
                login_path:                     oro_distribution_security_login
                default_target_path:            oro_distribution_package_listinstalled
                always_use_default_target_path: true
                csrf_provider:                  form.csrf_provider
            remember_me:
                key:                        %secret%
                name:                       BAPRM_DIST
                lifetime:                   1209600   # stay logged for two weeks
                httponly:                   true
            anonymous:                        ~
            logout:
              path:   /logout
              target: /

    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/packages, role: ROLE_ADMINISTRATOR }
        - { path: ^/$, role: ROLE_ADMINISTRATOR }
```

vendor/oro/platform/src/Oro/Bundle/EmbeddedFormBundle/Resources/config/oro/app.yml:
```
security:
    firewalls:
        embedded_form:
            pattern:   ^/embedded-form/(submit|success)
            provider:  chain_provider
            anonymous: true

```

vendor/oro/platform/src/Oro/Bundle/SecurityBundle/Resources/config/oro/app.yml:
```
security:
    acl:
        connection: default
        cache:
            id: security.acl.cache.doctrine
            prefix: sf2_acl_

    access_decision_manager:
        strategy: unanimous
        allow_if_all_abstain: true
```

vendor/oro/platform/src/Oro/Bundle/SoapBundle/Resources/config/oro/app.yml:
```
security:
    firewalls:
        wsse_secured:
            pattern: ^/api/rest.*
            stateless:  true
            wsse:
                lifetime: 3600
                realm:    "Secured API"
                profile:  "UsernameToken"
            context: main
```

vendor/oro/platform/src/Oro/Bundle/SSOBundle/Resources/config/oro/app.yml:
```
security:
    firewalls:
        main:
            oauth:
                resource_owners:
                    google: /login/check-google
                login_path: oro_user_security_login
                failure_path: oro_user_security_login
                check_path: oro_user_security_check
                oauth_user_provider:
                    service: oro_sso.oauth_provider
```

vendor/oro/platform/src/Oro/Bundle/UserBundle/Resources/config/oro/app.yml:
```
security:
    providers:
        chain_provider:
            chain:
                providers:                  [in_memory, oro_user]
        oro_user:
            id:                             oro_user.security.provider
        in_memory:
            memory:
                users:                      []

    encoders:
        Oro\Bundle\UserBundle\Entity\User: sha512

    firewalls:
        login:
            pattern:                        ^/user/(login|reset-request|send-email|check-email)$
            provider:                       chain_provider
            anonymous:                      true
            context:                        main

        reset_password:
            pattern:                        ^/user/reset/*
            provider:                       chain_provider
            anonymous:                      true

        main:
            pattern:                        ^/
            provider:                       chain_provider
            organization-form-login:
                csrf_provider:              form.csrf_provider
                check_path:                 oro_user_security_check
                login_path:                 oro_user_security_login
                default_target_path:        oro_default
            logout:
                path:                       oro_user_security_logout
            organization-remember-me:
                key:                        %secret%
                name:                       BAPRM
                lifetime:                   1209600   # stay logged for two weeks
                httponly:                   true
            anonymous:                      false
            guard:
                authenticators:
                    - oro_user.impersonation_authenticator
```

2. I tried to run this command:
`php vendor/phpunit/phpunit/phpunit --testsuite functional-1-of-10`
Downgrade to crm 2.3 and commerce 2.3: the error disappeared and I'm able to run functional tests.
