### ISSUE TITLE
How do I disable token lifetime in WSSE Authentication?

### ISSUE THREAD

**Issue by pedrofurtado** [oroinc/platform#805]
How do I disable token lifetime (i.e., to make tokens not expirable) in WSSE Authentication?

**Comment by vsoroka** [comment]
It is not possible to disable the token lifetime, but you can set a very big value for it, e.g. 30 days.
To do it you can use **/app/config/security.yml**.
Here is an example:
```yaml
security:
    firewalls:
        wsse_secured:
            wsse:
                lifetime: 2592000 # 30 days
        api_wsse_secured:
            wsse:
                lifetime: 2592000 # 30 days
```
