### ISSUE TITLE
Bug: Datagrid Fillter with type Choice and default value does not work correctly on v2.6.1

### ISSUE THREAD

**Issue by NikDevPHP** [oroinc/platform#836]
I set the default value for the status and it worked but when I press the X, values in the grid are not reset, but remain the filtered  by default value. Example of a filter configuration in datagrid:
Datagrid filter
```yaml
filters:
    columns:
        status:
	    type: choice
	    data_name: status.id
	    options:
	        field_options:
		    choices: "@example.manager.status->getList"
    default:
        vehicleStatus:
            value: "@example.manager.status->getAvailableStatusId"
```
