### ISSUE TITLE
Attachment file is not initialised properly

### ISSUE THREAD

**Issue by tautelis** [oroinc/platform#843]
Hey,

Attachment File is not initialised properly.

This happens while requesting `/admin/api/userprofile`.

services definition:
````
services:
    acme.api.get.acme_processor:
        class: AcmeBundle\Api\Processor\Get\AcmeProcessor
        arguments:
            - '@doctrine'
        tags:
            - { name: oro.api.processor, action: get, group: normalize_result, class: Oro\Bundle\UserBundle\Api\Model\UserProfile }
````
the class:

```
<?php

namespace AcmeBundle\Api\Processor\Get;

use Doctrine\Bundle\DoctrineBundle\Registry;
use Oro\Bundle\AttachmentBundle\Entity\File;
use Oro\Component\ChainProcessor\ContextInterface;
use Oro\Component\ChainProcessor\ProcessorInterface;

class AcmeProcessor implements ProcessorInterface
{
    /** @var Registry */
    protected $registry;

    /**
     * {@inheritdoc}
     */
    public function process(ContextInterface $context)
    {
        $fileRepository = $this->registry->getRepository(File::class);

        $file = $fileRepository->find(1);
        $filename = $file->getFilename();
        // here the $filename is null and entity __isInitialized__=true

        $fileRepository->clear();
        $file = $fileRepository->find(1);
        $filename = $file->getFilename();
        // here the $filename has correct value
    }
```

NOTE: if I initialise File at Oro\Bundle\ApiBundle\Controller\RestApiController::itemAction it is loaded correctly
