### ISSUE TITLE
Unrecognized option "link_attributes" 

### ISSUE THREAD

**Issue by sbardascione** [oroinc/platform#845]
Hello, /src/Oro/Bundle/NavigationBundle/
i'm tryng to add "link_attributes", it returns
```
Unrecognized option "link_attributes" under "oro_navigation.menu_config.items.<my_key>"
```
Here is my navigation.yml
 ```
navigation:
    menu_config:
        items:
            <my_key>:
                label: 'a_label_of_mine'
                route: route_id
                link_attributes: ['target=_blank']
        tree:
            application_menu:
                children:
                    <my_key>: ~

```

Thanks in advance
