### ISSUE TITLE
Unable to install application if default_locale is not "en"

### ISSUE THREAD

**Issue by vtsykun** [oroinc/platform#899]
**STR**
1) Set default local 'es_ES'

```yml
framework:
    default_locale:           '%locale%'
```

```yml
parameters:
    locale: es_ES
```

Run command oro:platform:install 

**Actual result**
```
  > loading Oro\Bundle\WorkflowBundle\Migrations\Data\ORM\UpdateDefinitionTranslations

In Translation.php line 104:
                                                                               
  Type error: Argument 1 passed to Oro\Bundle\TranslationBundle\Entity\Transl  
  ation::setLanguage() must be an instance of Oro\Bundle\TranslationBundle\En  
  tity\Language, null given, called in /var/www/cuantic/application/otek/vend  
  or/oro/platform/src/Oro/Bundle/TranslationBundle/Manager/TranslationManager  
  .php on line 81                                                              
                                                                               

oro:migration:data:load [--fixtures-type [FIXTURES-TYPE]] [--dry-run] [--bundles [BUNDLES]] [--exclude [EXCLUDE]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--disabled-listeners DISABLED-LISTENERS] [--current-user CURRENT-USER] [--current-organization CURRENT-ORGANIZATION] [--] <command>

The command '/usr/bin/php7.1' 'bin/console' 'oro:migration:data:load' '--no-interaction' '--no-debug' terminated with an exit code: 255.
```
**Expected result**
* Application should be installed without errors
* Spanish translations should be loaded (it works before 3.1)
![Selection_999(168)](https://user-images.githubusercontent.com/21358010/54377893-2964f900-4697-11e9-87b6-7467d03940d4.png)

* User must see Spanish login page (it works before 3.1)

**Comment by sadortun** [comment]
This issue is still valid, i got the same error with french

**Comment by vtsykun** [comment]
Hi @sadortun yes. I use the `oro_locale.language` config instead of `default_locale`

```yml
parameters:
    parameters:
framework:
    #esi:             ~
        fallback: en
        default_locale: en
stof_doctrine_extensions:
    default_locale: en
    translation_fallback: true
oro_locale:
    formatting_code: '%locale%'
    language: '%locale%'
```
