### ISSUE TITLE
Tags with multiple words are broken down

### ISSUE THREAD

**Issue by sadortun** [oroinc/platform#919]
Hi Oro Team,

Small UI bug that is quite anoying :( 

When tags contains multiple words, the words are broken down on multiple lines
For example : 

![image](https://user-images.githubusercontent.com/794449/58388398-549b8b00-7fec-11e9-963b-4258bbbcf512.png)

![image](https://user-images.githubusercontent.com/794449/58388413-70069600-7fec-11e9-98a1-58fb44180601.png)

Seems like a simple addition to CSS can fix the issue:
```css
.tags-container__tag-entry {
    white-space: nowrap;
}
```

Have a good day,
Samuel
