### ISSUE TITLE
Bug UI:  Segment filter does not "stretch" when value names are long

### ISSUE THREAD

**Issue by sadortun** [oroinc/platform#921]
Hi Oro Team,

Quick issue with the segment filter: 

As you can see, the last value is not displayed since the line wrap is discarded.

![image](https://user-images.githubusercontent.com/794449/58430016-bd7b1580-8075-11e9-9da9-e4d17d19481c.png)

Have a good day,
Samuel

**Comment by sadortun** [comment]
Issue come from 

```css
.condition-item .select2-container {
    height: 24px;
}
```

that should probably be `min-height`
