### ISSUE TITLE
The dialog width option is ignored. 

### ISSUE THREAD

**Issue by vtsykun** [oroinc/platform#946]
Hi, 

The styles of following dialog widgets are broken after update

**1) Email template**. oro/platform 3.1.10 
![Selection_999(394)](https://user-images.githubusercontent.com/21358010/62700673-29b9b400-b9eb-11e9-8a41-488ea7142fdc.png)

Before (oro/platform 2.6.*)

![Selection_999(393)](https://user-images.githubusercontent.com/21358010/62700702-43f39200-b9eb-11e9-81a0-19a6623ced5d.png)

**2) Operation frontend options does not apply**
```yml
operations:
    segment_help:
        label: cuantic.segment.about.dql
        frontend_options:
            options:
                allowMaximize: false
                allowMinimize: false
                dblclick: maximize
                width: 780
                height: 40%
```

Dialog width is ignored and overwrote by `important` rule 
![Selection_999(392)](https://user-images.githubusercontent.com/21358010/62701099-1e1abd00-b9ec-11e9-98d5-21c2cfd3b898.png)

Thanks,
Uladzimir
